name: Terraform Destroy

on:
  workflow_dispatch: # 

jobs:
  terraform-destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform initialization
        run: terraform init

      - name: Destroy infrastructure
        run: |
          terraform destroy -auto-approve \
            -var='cidr_block=10.0.0.0/16' \
            -var='project_name=my-project' \
            -var='region=us-east-1' \
            -var='tags={ Department = "DevOps", Organization = "Infrastructure and Operations", Project = "EKS", Environment = "Development" }'
