name: Terraform Action

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose the action'
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar o Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Inicializar o Terraform
        run: terraform init

      - name: Executar ação condicional do Terraform
        run: |
          if [ "${{ github.event.inputs.action }}" = "destroy" ]; then
            echo " Executando terraform destroy..."
            terraform destroy -auto-approve
          else
            echo " Executando terraform apply..."
            terraform plan -out=tfplan
            terraform apply -auto-approve tfplan
          fi
