name: Terraform Cluster EKS

on:
  workflow_dispatch: 

jobs:
  terraform:
    name: Workflow Terraform 
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform initialization
        run: terraform init

      - name: Format and Validate
        run: terraform fmt && terraform validate

      - name: Run Terraform Plan
        run: |
          terraform plan -out=tfplan \
            -var='cidr_block=10.0.0.0/16' \
            -var='project_name=my-project' \
            -var='region=us-east-1' \
            -var='tags={ Department = "DevOps", Organization = "Infrastructure and Operations", Project = "EKS", Environment = "Development" }'

      - name: Apply Terraform Apply
        run: terraform apply -auto-approve tfplan
